logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    standard:
      format: "%(asctime)s - %(levelname)s - %(name)s - %(filename)s:%(lineno)d - %(message)s"


  handlers:
    timed_file_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: INFO
      formatter: standard
      filename: logs/ragvsgraphrag.log
      when: midnight
      interval: 1
      backupCount: 2
      encoding: utf8
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [timed_file_handler, console]
